"""empty message

Revision ID: 8804dee075d9
Revises: 3c0bc780163b
Create Date: 2023-06-05 08:18:47.575803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8804dee075d9'
down_revision = '3c0bc780163b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_cover_images',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('pin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['pin_id'], ['pins.id'], ),
    sa.PrimaryKeyConstraint('board_id', 'pin_id')
    )
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.VARCHAR(length=255), nullable=True))

    op.drop_table('board_cover_images')
    # ### end Alembic commands ###
